# Generated by Django 6.0 on 2025-12-22 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni_cuit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='core_client_apellid_d2208f_idx'), models.Index(fields=['dni_cuit'], name='core_client_dni_cui_2d4e6d_idx'), models.Index(fields=['telefono'], name='core_client_telefon_b0f36d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('marca_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('problema_reportado', models.TextField()),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True)),
                ('solucion_implementada', models.TextField(blank=True, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado_actual', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Diagnóstico', 'En Diagnóstico'), ('En Reparación', 'En Reparación'), ('En Espera de Repuestos', 'En Espera de Repuestos'), ('Listo para Retirar', 'Listo para Retirar'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], db_index=True, default='Pendiente', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.cliente')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Diagnóstico', 'En Diagnóstico'), ('En Reparación', 'En Reparación'), ('En Espera de Repuestos', 'En Espera de Repuestos'), ('Listo para Retirar', 'Listo para Retirar'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='core.servicio')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['estado_actual'], name='core_servic_estado__6cd6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['fecha_ingreso'], name='core_servic_fecha_i_5cea94_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['fecha_entrega'], name='core_servic_fecha_e_821470_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['tipo_equipo'], name='core_servic_tipo_eq_d61d22_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestado',
            index=models.Index(fields=['fecha_cambio'], name='core_histor_fecha_c_56b5a5_idx'),
        ),
    ]
