# Generated by Django 6.0 on 2026-07-17 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=160, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.servicio')),
            ],
            options={
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['fecha_subida'], name='core_servic_fecha_s_078587_idx')],
            },
        ),
    ]
